INSERT INTO SYS_USER(ID, USERNAME, PASSWORD) VALUES (1,'wen','wen');
INSERT INTO SYS_USER(ID, USERNAME, PASSWORD) VALUES (2,'tan','tan');

INSERT into SYS_ROLE(ID,NAME) VALUES (1,'role_admin');
INSERT into SYS_ROLE(ID,NAME) VALUES (2,'role_user');

INSERT INTO SYS_USER_ROLES(SYS_USER_ID, ROLES_ID) VALUES (1,1);
INSERT INTO SYS_USER_ROLES(SYS_USER_ID, ROLES_ID) VALUES (2,2);